version: '3.0'

services:
  db:
    image: redcrafter07/redi-db:0.3
    ports:
      - 12018:12018
    expose:
      - 12018
    environment:
      - USER=user #Change - Default user (admin), currently the only user available
      - PASSWORD=password #Change - Password for default user
      - PORT=12018
    volumes:
      - redi-db:/data:rw

volumes:
  redi-db: